/*chisq*/
%macro chisq(adj=F);
%if &adj eq F %then 
%put &str 使用的分析方法是卡方(未调整);
%else %put &str 使用的是调整后卡方;
proc freq data=&ds;
table &str * &grp /chisq ;
ods output chisq=chisq_&cat_id(where=(Statistic=%if &adj=F %then "卡方"; %else "连续调整卡方";) keep=statistic prob);
ods select chisq ;
run;
ods output close;
data chisq_&cat_id;
set chisq_&cat_id(drop=statistic);
pvalue=put(prob,6.4);
drop prob;
run;
%data_merge(cat_&cat_id,freq_table_&cat_id,chisq_&cat_id);
%mend;
/*fisher*/
%macro fisher();
%put &str 使用的是Fisher确切概率法!;
proc freq data=&ds ;
table &str * &grp ;
exact fisher;
ods output fishersexact=fisher_&cat_id(where=(name1="XP2_FISH")keep=name1 cvalue1);
ods select fishersexact;
run;
ods output close;
data fisher_&cat_id;
set fisher_&cat_id(drop=name1);
pvalue=cvalue1||"*";
drop cvalue1;
run;
%data_merge(cat_&cat_id,freq_table_&cat_id,fisher_&cat_id);
%mend;
/*CA*/
%macro ca_test();
%put &str 使用的是CA趋势检验;
proc freq data=&ds;
table &str*&grp /trend;
ods output trendtest=trend_&cat_id(where=(Name1="P2_TREND" keep=cvalue1));
ods select trendtest;
run;
ods output close;
data trend_&cat_id;
set trend_&cat_id(drop=name1);
pvalue=cvalue1||"**";
drop cvalue1;
run;
%data_merge(cat_&cat_id,freq_table_&cat_id,trend_&cat_id);
%mend;
/*match*/
%macro match_test();
%put &str 使用的是配对检验(对称性检验);
proc freq data=&ds;
table &str * &grp /agree;
%if &n_level_grp = 2 %then %do;
ods output mcnemarsTest=agree_&cat_id(keep=prob);
ods select mcnemarsTest;
%end;
%else %do;
ods output SymmetryTest=agree_&cat_id(keep=prob);
ods select SymmetryTest;
run;
%end;
run;
ods output close;
data agree_&cat_id;
set agree_&cat_id;
pvalue=prob||"***";
drop prob;
run;
%data_merge(cat_&cat_id,freq_table_&cat_id,agree_&cat_id);
%mend;
/*kappa*/
%macro agree();
%put &str 使用的是Kappa！;
proc freq data=&ds;
table &str * &grp /agree;
ods output kappaStatistics=kappa_&cat_id(keep=Value);
ods select kappaStatistics;
run;
ods output close;
data kappa_&cat_id;
set kappa_&cat_id;
pvalue=value||"$";
drop value;
run;
%data_merge(cat_&cat_id,freq_table_&cat_id,kappa_&cat_id);
%mend;
